services/backend/thiamsu/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path, re_path

from . import views
from .apis import SongList

urlpatterns = [
    re_path(r"^$", views.home, name="home"),
    re_path(r"^form/account_deletion", views.account_deletion, name="account_deletion"),
    re_path(r"^policies/privacy", views.privacy_policy, name="policy_privacy"),
    re_path(r"^search/$", views.search, name="search"),
    re_path(r"^song/(?P<id>[0-9]*)/$", views.song_detail, name="song_detail"),
    re_path(r"^song/(?P<id>[0-9]*)/edit/$", views.song_edit, name="song_edit"),
    re_path(
        r"^song/(?P<id>[0-9]*)/translation/$",
        views.song_translation_post,
        name="song_translation_post",
    ),
    re_path(r"^user/(?P<id>[0-9]+)/$", views.user_profile, name="user_profile"),
    re_path(r"^chart/$", views.chart, name="chart"),
    re_path(r"^grappelli/", include("grappelli.urls")),
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^logout/$", auth_views.LogoutView.as_view(), name="logout"),
    re_path(r"^oauth/", include("social_django.urls", namespace="social")),
    re_path(
        r"^api/user/favorite_song/$",
        views.api_user_favorite_song,
        name="api_user_favorite_song",
    ),
    path("api/song/", SongList.as_view()),
    path("tinymce/", include("tinymce.urls")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [re_path(r"^__debug__/", include(debug_toolbar.urls))] + urlpatterns

services/backend/thiamsu/models/hanzi_hanlo_mapping.py
# third-party
from django.core.cache import cache
from django.db import models
from django.utils.translation import gettext_lazy as _


class HanziHanloMapping(models.Model):
    hanzi = models.CharField(
        _("hanzi_hanlo_mapping_hanzi"), max_length=100, unique=True
    )
    hanlo = models.CharField(_("hanzi_hanlo_mapping_hanlo"), max_length=100)

    def __str__(self):
        return "%s -> %s" % (self.hanzi, self.hanlo)

    class Meta:
        verbose_name = _("hanzi_hanlo_mapping")
        verbose_name_plural = _("hanzi_hanlo_mappings")

    @classmethod
    def dump(cls, force=False):
        if force or "hanzi_hanlo_mapping" not in cache:
            mapping = {obj.hanzi: obj.hanlo for obj in cls.objects.all()}
            cache.set("hanzi_hanlo_mapping", mapping)
        return cache.get("hanzi_hanlo_mapping")

services/backend/thiamsu/models/headline.py
# third-party
from django.db import models
from django.utils.translation import gettext_lazy as _

# local
from thiamsu.models.song import Song


class Headline(models.Model):
    song = models.ForeignKey(Song, verbose_name=_("song"), on_delete=models.CASCADE)
    start_time = models.DateTimeField(_("headline_start_time"))
    end_time = models.DateTimeField(_("headline_end_time"))

    class Meta:
        verbose_name = _("headline")
        verbose_name_plural = _("headlines")

services/backend/thiamsu/models/new_word.py
# third-party
from django.db import models
from django.utils.translation import gettext_lazy as _

# local
from thiamsu.models.song import Song


class NewWord(models.Model):
    song = models.ForeignKey(Song, verbose_name=_("song"), on_delete=models.CASCADE)
    content = models.CharField(_("new_word_content"), max_length=100)
    reference_url = models.CharField(_("new_word_reference_url"), max_length=1000)

    created_at = models.DateTimeField(_("new_word_created_at"), auto_now_add=True)

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = _("new_word")
        verbose_name_plural = _("new_words")

        unique_together = ("song", "content", "reference_url")

services/backend/thiamsu/models/privacy_policy.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from solo.models import SingletonModel
from tinymce.models import HTMLField


class PrivacyPolicy(SingletonModel):
    title = models.CharField(_("privacy_policy_title"), max_length=100)
    body = HTMLField(_("privacy_policy_content"))

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("privacy_policy_verbose_name")

services/backend/thiamsu/models/song.py
from itertools import combinations

from django.db import models
from django.db.models import Q
from django.utils.translation import gettext_lazy as _
from embed_video.fields import EmbedVideoField
from unidecode import unidecode

from thiamsu.utils import get_youtube_id_from_url, translate_hanzi_to_hanlo


def _to_alias(word):
    return unidecode(word.replace("-", " "))


def split_to_keyword_groups(keyword):
    segments = [k for k in keyword.split() if k.strip()]
    groups = []
    for n in range(len(segments) - 1, 1, -1):
        groups += tuple(combinations(segments, n))
    return [" ".join(g) for g in set(groups)]


class Song(models.Model):
    original_title = models.CharField(_("song_original_title"), max_length=100)
    hanzi_title = models.CharField(_("song_hanzi_title"), max_length=100)
    tailo_title = models.CharField(_("song_tailo_title"), max_length=100)
    hanlo_title = models.CharField(_("song_hanlo_title"), max_length=100)
    performer = models.CharField(_("song_performer"), max_length=100)
    hanlo_performer = models.CharField(_("song_hanlo_performer"), max_length=100)
    composer = models.CharField(_("song_composer"), max_length=100)
    lyricist = models.CharField(_("song_lyricist"), max_length=100)
    youtube_url = EmbedVideoField(_("song_youtube_url"))
    original_lyrics = models.TextField(_("song_original_lyrics"), default="")
    readonly = models.BooleanField(_("song_readonly"), default=False)
    progress = models.PositiveSmallIntegerField(_("song_progress"), default=0)

    title_alias = models.CharField(max_length=100, blank=True)
    performer_alias = models.CharField(max_length=100, blank=True)

    created_at = models.DateTimeField(_("song_created_at"), auto_now_add=True)

    class Meta:
        verbose_name = _("song")
        verbose_name_plural = _("songs")

    @staticmethod
    def autocomplete_search_fields():
        return ("id__iexact", "original_title__icontains")

    def __str__(self):
        return u"%s (%s)" % (self.original_title, self.performer)

    def save(self, *args, **kwargs):
        # remove excess whitespace to improve search result
        for field in [
            "original_title",
            "hanzi_title",
            "tailo_title",
            "hanlo_title",
            "performer",
            "hanlo_performer",
        ]:
            self.__dict__[field] = " ".join(self.__dict__[field].split())

        self.title_alias = _to_alias(self.tailo_title)
        self.performer_alias = _to_alias(self.hanlo_performer)
        super().save(*args, **kwargs)

    @classmethod
    def search_title(cls, keyword):
        exact_match = cls.objects.filter(
            Q(original_title__icontains=keyword)
            | Q(hanzi_title__icontains=keyword)
            | Q(tailo_title__icontains=keyword)
            | Q(title_alias__icontains=_to_alias(keyword))
        )

        # 'a b c d' to ['a c d', 'a b c', 'b c d', 'a b d', 'b d', 'c d', 'a b', 'b c', 'a c', 'a d']
        keyword_groups = split_to_keyword_groups(keyword)
        multi_match = cls.objects.filter(
            Q(original_title__icontains=keyword_groups)
            | Q(hanzi_title__icontains=keyword_groups)
            | Q(tailo_title__icontains=keyword_groups)
            | Q(title_alias__icontains=[_to_alias(g) for g in keyword_groups])
        )

        # 'a b c' to ['a', 'b', 'c']
        single_match = cls.objects.filter(
            Q(original_title__icontains=keyword.split())
            | Q(hanzi_title__icontains=keyword.split())
            | Q(tailo_title__icontains=keyword.split())
            | Q(title_alias__icontains=_to_alias(keyword).split())
        )
        return (exact_match | multi_match | single_match).distinct()

    @classmethod
    def search_performer(cls, keyword):
        exact_match = cls.objects.filter(
            Q(performer__icontains=keyword)
            | Q(hanlo_performer__icontains=keyword)
            | Q(performer_alias__icontains=_to_alias(keyword))
        )

        # 'a b c d' to ['a c d', 'a b c', 'b c d', 'a b d', 'b d', 'c d', 'a b', 'b c', 'a c', 'a d']
        keyword_groups = split_to_keyword_groups(keyword)
        multi_match = cls.objects.filter(
            Q(performer__icontains=keyword_groups)
            | Q(hanlo_performer__icontains=keyword_groups)
            | Q(performer_alias__icontains=[_to_alias(g) for g in keyword_groups])
        )

        # 'a b c' to ['a', 'b', 'c']
        single_match = cls.objects.filter(
            Q(performer__icontains=keyword.split())
            | Q(hanlo_performer__icontains=keyword.split())
            | Q(performer_alias__icontains=_to_alias(keyword).split())
        )
        return (exact_match | multi_match | single_match).distinct()

    @property
    def youtube_id(self):
        return get_youtube_id_from_url(self.youtube_url)

    @property
    def cover_url(self):
        return "https://img.youtube.com/vi/{id}/hqdefault.jpg".format(
            id=self.youtube_id
        )

    def get_translations(self, lang):
        from thiamsu.models.translation import Translation

        latest_translation_times = (
            Translation.objects.filter(song=self.id)
            .filter(lang=lang)
            .values("line_no")
            .annotate(models.Max("created_at"))
            .order_by()
        )

        q_statement = models.Q()
        for pair in latest_translation_times:
            q_statement |= models.Q(line_no__exact=pair["line_no"]) & models.Q(
                created_at__exact=pair["created_at__max"]
            )
        translations = (
            Translation.objects.filter(song=self.id)
            .filter(lang=lang)
            .filter(q_statement)
        )
        return {t.line_no: t.content for t in translations}

    def get_lyrics_with_translations(self):
        hanzi_lyrics = self.get_translations("hanzi")
        tailo_lyrics = self.get_translations("tailo")
        hanlo_lyrics = self.get_translations("hanlo")

        lyrics_with_translations = []
        for i, lyric in enumerate(self.original_lyrics.split("\n")):
            lyrics_with_translations.append(
                {
                    "original": lyric,
                    "hanzi": hanzi_lyrics.get(i),
                    "tailo": tailo_lyrics.get(i),
                    "hanlo": hanlo_lyrics.get(i),
                }
            )
        return lyrics_with_translations

    def get_new_words(self):
        from thiamsu.models.new_word import NewWord

        return NewWord.objects.filter(song=self)

    def create_hanlo_lyrics(self):
        from thiamsu.models.translation import Translation

        hanzi_lyrics = self.get_translations("hanzi")
        hanlo_lyrics = self.get_translations("hanlo")
        for line_no, hanzi_lyric in hanzi_lyrics.items():
            if hanlo_lyrics.get(line_no):
                continue

            new_translation = Translation(
                song=self,
                line_no=line_no,
                lang="hanlo",
                content=translate_hanzi_to_hanlo(hanzi_lyric),
                contributor=None,
            )
            new_translation.save()
            print(line_no, "translated")

services/backend/thiamsu/models/translation.py
# third-party
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _

# local
from thiamsu.models.song import Song


class Translation(models.Model):
    LANG_CHOICES = (
        ("tailo", _("translation_lang_tailo")),
        ("hanzi", _("translation_lang_hanzi")),
        ("hanlo", _("translation_lang_hanlo")),
    )

    song = models.ForeignKey(Song, verbose_name=_("song"), on_delete=models.CASCADE)
    line_no = models.PositiveSmallIntegerField(_("translation_line_no"))
    lang = models.CharField(_("translation_lang"), max_length=5, choices=LANG_CHOICES)
    content = models.CharField(_("translation_content"), max_length=1000)
    contributor = models.ForeignKey(
        User,
        blank=True,
        null=True,
        verbose_name=_("translation_contributor"),
        on_delete=models.CASCADE,
    )

    created_at = models.DateTimeField(_("translation_created_at"), auto_now_add=True)

    def get_original_lyric(self):
        return self.song.original_lyrics.split("\n")[self.line_no]

    get_original_lyric.short_description = _("song_original_lyrics")
    original_lyric = property(get_original_lyric)

    class Meta:
        verbose_name = _("translation")
        verbose_name_plural = _("translations")

    @staticmethod
    def autocomplete_search_fields():
        return ("song__original_title__icontains",)

services/backend/thiamsu/forms.py
from django import forms
from django.forms import formset_factory
from django.forms.formsets import BaseFormSet
from django.forms.widgets import HiddenInput

from thiamsu.utils import get_youtube_id_from_url


class SongAdminForm(forms.ModelForm):
    def clean_youtube_url(self):
        youtube_id = get_youtube_id_from_url(self.cleaned_data["youtube_url"])
        if not youtube_id:
            raise forms.ValidationError(
                "Invalid URL: %(url)s",
                code="invalid youtube url",
                params={"url": self.cleaned_data["youtube_url"]},
            )
        return self.cleaned_data["youtube_url"]


class TranslationForm(forms.Form):
    line_no = forms.IntegerField(widget=forms.HiddenInput)
    lang = forms.CharField(max_length=5, widget=forms.HiddenInput)
    content = forms.CharField(max_length=1000, required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["line_no"].widget.attrs["readonly"] = True
        self.fields["lang"].widget.attrs["readonly"] = True


class BaseTranslationFormSet(BaseFormSet):
    def __init__(self, original_lyrics=None, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # set original lyric as label of each line
        if not original_lyrics or len(original_lyrics) != len(self.forms):
            return
        for i, form in enumerate(self.forms):
            form.fields["content"].label = original_lyrics[i]


TranslationFormSet = formset_factory(
    TranslationForm, formset=BaseTranslationFormSet, extra=0
)


class SongReadonlyForm(forms.Form):
    readonly = forms.BooleanField(required=False)


class UserFavoriteSongForm(forms.Form):
    method = forms.ChoiceField(choices=[(m, m) for m in ("POST", "DELETE")])
    song_id = forms.IntegerField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["method"].widget = HiddenInput()
        self.fields["song_id"].widget = HiddenInput()

services/backend/thiamsu/templates/thiamsu/_player_with_info.html
<div class="player">
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item"
                src="https://www.youtube.com/embed/{{ song.youtube_id }}?playsinline=1"
                referrerpolicy="no-referrer-when-downgrade"
                frameborder="0" allowfullscreen></iframe>
    </div>
</div>

<div class="song-information">
    <p class="original-title">{{ song.original_title }}</p>

    <div class="translated-titles">
        <p class="translated-title tailo">{{ song.hanlo_title }}</p>
        <p class="translated-title hanzi">{{ song.hanzi_title }}</p>
        <p class="translated-title tailo">{{ song.tailo_title }}</p>
    </div>

    <div class="authors">
        <p class="performer">演唱人：{{ song.performer }}</p>
        <p class="composer">作曲人：{{ song.composer }}</p>
        <p class="lyricist">作詞人：{{ song.lyricist }}</p>
    </div>
</div>

services/backend/thiamsu/templates/thiamsu/account_deletion.html
{% extends 'thiamsu/base.html' %}
{% load static %}

{% block content %}
<iframe class="airtable-embed" src="https://airtable.com/embed/shrTVEQ2LObXscTtp?backgroundColor=gray" frameborder="0" onmousewheel="" width="100%" height="958" style="background: transparent; border: 1px solid #ccc;"></iframe>
{% endblock %}

services/backend/thiamsu/templates/thiamsu/base.html
{% load static song_search %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% if ga_tracking_id %}
        {% include "thiamsu/ga.html" %}
    {% endif %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block page_title %}歌詞正字{% endblock %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel="stylesheet" href="{% static "thiamsu/css/main.css" %}">
    <script src="{% static "thiamsu/js/search.js" %}"></script>

</head>
<body>
    <div class="container theme-thiamsu">

        <div class="header{% if headline is not None %} has-headline"{% endif %}">

            {# Background of Headline #}
            {% if headline is not None  %}
                <div class="headline-background">
                    <img src="{{ headline.cover_url }}">
                </div>
            {% endif %}

            {# Navigation Bar #}
            <nav class="row">

                {# Title & Subtitle #}
                <div>
                    <a class="header-title" href="/">歌詞正字</a>
                    <p class="header-subtitle">台語歌詞共同編修平台</p>
                </div>

                {# Chart Link & Search Form #}
                <div class="nav-secondary nav-block">
                    <div class="nav-chart">
                        {% if headline %}
                            <img src="{% static "thiamsu/img/ico-chart-w.png" %}"
                                 srcset="{% static "thiamsu/img/ico-chart-w@2x.png" %} 2x,
                                         {% static "thiamsu/img/ico-chart-w@3x.png" %} 3x">
                        {% else %}
                            <img src="{% static "thiamsu/img/ico-chart-b.png" %}"
                                 srcset="{% static "thiamsu/img/ico-chart-b@2x.png" %} 2x,
                                         {% static "thiamsu/img/ico-chart-b@3x.png" %} 3x">
                        {% endif %}
                        <a href="/chart">排行榜</a>
                    </div>

                    <form id="search-form" method="get" action="/search">
                        <div class="input-group">
                            <input id="search-text" name="keyword" class="form-control" type="text" placeholder="搜尋歌曲" value="{{ query|default_if_none:"" }}">
                            <input id="search-type" name="type" type="hidden" value="{% current_search_type %}">

                            <span class="input-group-btn">
                                <button id="search-type-select" class="btn btn-search-type dropdown-toggle" type="button" data-toggle="dropdown">{% current_search_type_label %}</button>
                                <div class="dropdown-menu dropdown-menu-right">
                                    {% all_search_types as search_types %}
                                    {% for st in search_types %}
                                        <a class="dropdown-item" data-value="{{ st }}">{% search_type_label_of st %}</a>
                                    {% endfor %}
                                </div>
                            </span>

                            <span class="input-group-btn">
                                <button class="btn btn-search" type="submit">
                                    <i class="material-icons align-middle">search</i>
                                </button>
                            </span>
                        </div>
                    </form>
                </div>

            </nav>

            {# Headline #}
            {% if headline is not None %}
                <div class="row headline">
                    <div class="col-4 col-lg-6">
                        <div class="embed-responsive embed-responsive-16by9">
                            <iframe class="embed-responsive-item"
                                    src="https://www.youtube.com/embed/{{ headline.youtube_id }}"
                                    referrerpolicy="no-referrer-when-downgrade"
                                    frameborder="0" allowfullscreen></iframe>
                        </div>
                    </div>
                    <div class="col-8 col-lg-6">
                        <div class="headline-label">最新消息</div>
                        <a href="{% url 'song_detail' id=headline.id %}" class="title-link">
                            <div class="title">{{ headline.original_title }}</div>
                            <div class="title">{{ headline.tailo_title }}</div>
                        </a>
                        <div class="performer">{{ headline.performer }}</div>
                    </div>
                </div>
            {% endif %}

        </div>

        {% block content %}{% endblock %}

        <div class="footer">
            <div class="container">
                <div class="d-flex flex-column">
                    <div class="d-flex justify-content-center footer-title">
                        歌詞正字
                    </div>
                    <div class="d-flex justify-content-center footer-info">
                        指導單位：<strong>教育部</strong>
                        ｜本網站由李江却台語文教基金會製作，為非營利及非商業性使用，僅供學習及促進台語用字一致化之教育功能。
                        ｜<a href="https://youtu.be/scE0OiUMt4M" target="_blank" class="text-white">
                            <u>網站介紹</u>
                        </a>
                        ｜<a href="{% url "policy_privacy" %}" target="_blank" class="text-white">
                            <u>隱私權政策</u>
                        </a>
                    </div>
                </div>
            </div>
        </div>

    </div>
</body>
</html>

services/backend/thiamsu/templates/thiamsu/ga.html
<script async src="https://www.googletagmanager.com/gtag/js?id={{ ga_tracking_id }}"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', '{{ ga_tracking_id }}');
</script>

services/backend/thiamsu/templates/thiamsu/privacy_policy.html
{% extends 'thiamsu/base.html' %}
{% load static %}

{% block content %}
<div class="row policy">
    <h1 class="policy-title">
        {{ privacy_policy.title }}
    </h1>
    <div class="policy-body">
        {{ privacy_policy.body|safe }}
    </div>
</div>
{% endblock %}

services/backend/thiamsu/templates/thiamsu/song_detail.html
{% extends 'thiamsu/base.html' %}
{% load static %}

{% block page_title %}{{ song.original_title }} - {{ block.super }}{% endblock %}

{% block content %}
    <div class="row song-detail">

        <div class="col-12 col-lg-5">
            <div class="song-actions toolbar">
                {% if user.is_authenticated %}
                    {% if is_favorite_song %}
                        <form action='/api/user/favorite_song/' method='post'>
                            {% csrf_token %}
                            {{ favorite_form }}
                            <button class="btn btn-unfavorite" type="submit">取消收藏</button>
                        </form>
                    {% else %}
                        <form action='/api/user/favorite_song/' method='post'>
                            {% csrf_token %}
                            {{ favorite_form }}
                            <button class="btn btn-favorite" type="submit">收藏</button>
                        </form>
                    {% endif %}
                {% else %}
                        <button class="btn btn-favorite" type="submit"
                                data-toggle="modal" data-target="#login-to-favorite"
                        >收藏</button>
                {% endif %}

                <a class="btn"
                   href="https://www.facebook.com/sharer/sharer.php?u={{ full_url|urlencode }}"
                   target="_blank"
                   onclick="window.open(this.href, 'fbShare', 'width=600,height=600'); return false;"
                >分享</a>
            </div>

            {% include 'thiamsu/_player_with_info.html' %}
        </div>

        <div class="col-12 col-lg-7">
            <div class="contribution toolbar">
                <div class="contributors">
                    <p>全漢編修人： {{ contributors.hanzi }}</p>
                    <p>全羅編修人： {{ contributors.tailo }}</p>
                </div>

                <div class="d-flex align-items-center">
                    {% if user.is_staff or user.is_superuser %}
                    <div class="lock-form-hint">編修鎖定</div>
                    <form id="song-lock-form" action='/song/{{ song.id }}/' method='post'>
                        {% csrf_token %}
                        {{ readonly_form }}
                        <button type="submit"
                                class="btn"
                                data-on="開啟"
                                data-off="鎖定" />
                    </form>
                    {% endif %}

                    <button type="button" class="btn btn-edit"
                            {% if song.readonly %}disabled{% endif %}
                            onclick="location.href='{% url 'song_edit' song.id %}'"
                    >鬥編修</button>
                </div>
            </div>

            <div class="lyric-wrapper">

                <input id="view-original-lyric" class="lyric-toggler" type="checkbox" checked disabled>
                <input id="view-hanzi-lyric" class="lyric-toggler" type="checkbox" name="lyric-visibility"
                    {% if lyric_visiblity.hanzi %}checked{% endif %}>
                {% if song.readonly %}
                    <input id="view-hanlo-lyric" class="lyric-toggler" type="checkbox" name="lyric-visibility"
                        {% if lyric_visiblity.hanlo %}checked{% endif %}>
                {% endif %}
                <input id="view-tailo-lyric" class="lyric-toggler" type="checkbox" name="lyric-visibility"
                    {% if lyric_visiblity.tailo %}checked{% endif %}>

                <div class="lyric-visiblities">
                    <label class="show-original" for="view-original-lyric">原文</label>
                    <label class="show-hanzi" for="view-hanzi-lyric">全漢</label>
                    {% if song.readonly %}
                        <label class="show-hanlo" for="view-hanlo-lyric">漢羅</label>
                    {% endif %}
                    <label class="show-tailo" for="view-tailo-lyric">全羅</label>
                </div>

                <ul class="lyric">
                {% for lyric in lyrics %}
                    <li>
                        <p class="lyric-line lyric-line-original show-original">{{ lyric.original }}</p>
                        {% if lyric.original|length > 0 %}
                            <p class="lyric-line lyric-line-translated show-hanzi">{{ lyric.hanzi|default_if_none:"-" }}</p>
                            {% if song.readonly %}
                                <p class="lyric-line lyric-line-translated show-hanlo">{{ lyric.hanlo|default_if_none:"-" }}</p>
                            {% endif %}
                            <p class="lyric-line lyric-line-translated show-tailo">{{ lyric.tailo|default_if_none:"-" }}</p>
                        {% else %}
                            <p>&nbsp;</p>
                        {% endif %}
                    </li>
                {% endfor %}
                </ul>

            </div>

            {% if new_words|length > 0 %}
            <div class="new-words-wrapper">
                生難詞：
                <ul class="new-words">
                    {% for word in new_words %}
                    <li><a href="{{ word.reference_url }}" target="_blank">{{ word.content }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}

        </div>

    </div>

    {% if user.is_authenticated %}
        {% if user.is_staff or user.is_superuser %}
        <script>
            $('#song-lock-form').submit(function (e) {
                $('#song-lock-form button[type=submit]').attr('disabled', 'disabled')
                var cb = $('#id_readonly')[0];
                cb.checked = !cb.checked;
            })
        </script>
        {% endif %}
    {% else %}
        <div class="modal fade modal-simple" id="login-to-favorite">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-body">
                        <img src="{% static "thiamsu/img/img-fav.png" %}"
                             srcset="{% static "thiamsu/img/img-fav@2x.png" %} 2x,
                                     {% static "thiamsu/img/img-fav@3x.png" %} 3x">
                        <h5>立即註冊即可將歌曲加入收藏</h5>
                        <a href="{% url 'social:begin' 'facebook' %}" role="button" class="btn btn-facebook-login">使用 Facebook 註冊/登入</button>
                        <a class="dismiss" href="#" data-dismiss="modal">下次再說</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade modal-simple" id="login-to-edit">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-body">
                        <img src="{% static "thiamsu/img/img-edit-lyrics.png" %}"
                             srcset="{% static "thiamsu/img/img-edit-lyrics@2x.png" %} 2x,
                                     {% static "thiamsu/img/img-edit-lyrics@3x.png" %} 3x">
                        <h5>立即註冊即可一起編修歌詞</h5>
                        <a href="{% url 'social:begin' 'facebook' %}" role="button" class="btn btn-facebook-login">使用 Facebook 註冊/登入</button>
                        <a class="dismiss" href="#" data-dismiss="modal">下次再說</a>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}